apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mercadinho-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mercadinho-api   # Deployment que será escalado
  minReplicas: 2           # mínimo de pods
  maxReplicas: 5           # máximo de pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
